version: "3.9"

services:
  web:
    container_name: my_web
    image: 389798/node-container
    build: .
    depends_on:
      - db
    volumes:
      - C:\Users\Игорь\Documents\adventure-open-api\ejs:/app/ejs
    ports:
      - 4000:4000

  db:
    image: postgres
    container_name: my_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rambler557
      - POSTGRES_DB=adventure
    ports:
      - 8080:5432
    volumes:
      - db-postgres:/var/lib/postgresql/data

networks:
  default:

volumes:
  db-postgres:
